[package]
name = "iota_oracle_tasks"
version = "0.0.1"
edition = "2024.beta"
published-at = "0x4586bab7b07a8dbeeb43770a7974bfcbb885f2e6985439cac1f28ecf58332892"

[dependencies]
iota_oracle_system_state = { local = "../oracle_system_state_testnet" }

[addresses]
iota_oracle_tasks = "0x4586bab7b07a8dbeeb43770a7974bfcbb885f2e6985439cac1f28ecf58332892"
